services:
  db:
    image: mysql:8.0.27
    environment:
      MYSQL_DATABASE: music
      MYSQL_USER: usr
      MYSQL_PASSWORD: password
      MYSQL_ROOT_PASSWORD: password 

  backend:
    build: ./backend/music
    ports:
      - 7070:7070
    depends_on:
      db:
        condition: service_healthy
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/music
      SPRING_DATASOURCE_USERNAME: usr
      SPRING_DATASOURCE_PASSWORD: password
      FINANCE_RABBITMQ_HOST: rabbitmq
    restart: always
