name: Deploy application

on:
  workflow_run:
    branches:
      - master
    workflows: ["Run API tests"]
    types:
      - completed

jobs:
  deploy_app:
    runs-on: ubuntu-latest

    steps:
      - name: Test
        run: echo "Action working"
